# Generated by Django 3.1.7 on 2021-03-05 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('IdCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('IdEstado', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('IdMarca', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('IdProducto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Precio', models.IntegerField()),
                ('Stock', models.IntegerField()),
                ('Gramage', models.CharField(max_length=30)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.categoria')),
                ('Estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.estado')),
                ('Marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['Nombre'],
            },
        ),
    ]
