# Generated by Django 3.1.7 on 2021-03-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20210305_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='Descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
