# Generated by Django 3.1.7 on 2021-03-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_auto_20210305_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('IdCliente', models.AutoField(primary_key=True, serialize=False)),
                ('Documento', models.IntegerField()),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['Nombre'],
            },
        ),
        migrations.AlterField(
            model_name='categoria',
            name='Nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre Categoria'),
        ),
    ]
