# Generated by Django 3.1.7 on 2021-03-12 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_auto_20210312_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('IdVenta', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Valor', models.IntegerField()),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.cliente')),
                ('Productos', models.ManyToManyField(to='Inventory.Producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
