# Generated by Django 3.1.7 on 2021-03-12 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='Productos',
        ),
        migrations.AlterField(
            model_name='producto',
            name='Categoria',
            field=models.ForeignKey(default='Seleccione su categoria', on_delete=django.db.models.deletion.CASCADE, to='Inventory.categoria'),
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(default=1)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.producto')),
                ('Venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.venta')),
            ],
        ),
    ]
