# Generated by Django 3.1.7 on 2021-03-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_auto_20210312_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='Fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
